/**
 * Valores usados quando a tabela `configuracoes` ainda não tem linha ou o fetch falha.
 * Chaves alinhadas com `sql/configuracoes.sql`.
 */
export const APP_CONFIG_KEYS = {
  SISTEMA_NOME: "sistema.app_nome",
  SISTEMA_URL_BASE: "sistema.url_base",
  SISTEMA_LOGO_URL: "sistema.logo_url",
  SISTEMA_COR_PRIMARIA: "sistema.cor_primaria",
  SISTEMA_COR_SECUNDARIA: "sistema.cor_secundaria",
  SISTEMA_COR_ACCENT: "sistema.cor_accent",
  SISTEMA_TIMEZONE: "sistema.timezone",
  SISTEMA_LOCALE: "sistema.locale",
  SISTEMA_CURRENCY: "sistema.currency",
  SISTEMA_MANUTENCAO: "sistema.manutencao",
  NEGOCIO_SCORE: "negocio.score",
  NEGOCIO_ECONOMIA: "negocio.economia",
  NEGOCIO_LIMITES: "negocio.limites",
  NEGOCIO_REGRAS_NEGOCIO: "negocio.regras_negocio",
  FINANCEIRO_CATEGORIAS: "financeiro.categorias",
  FINANCEIRO_TAXAS: "financeiro.taxas",
  FINANCEIRO_PAGAMENTOS: "financeiro.pagamentos",
  VIAGENS_STATUS: "viagens.status_padrao",
  VIAGENS_ALERTAS: "viagens.alertas",
  NOTIFICACOES_TEMPLATES: "notificacoes.templates",
  NOTIFICACOES_CANAIS: "notificacoes.canais",
  INTEGRACOES_DETALHES: "integracoes.detalhes",
} as const;

export const DEFAULT_APP_CONFIG: Record<string, unknown> = {
  [APP_CONFIG_KEYS.SISTEMA_NOME]: "Gest Miles",
  [APP_CONFIG_KEYS.SISTEMA_URL_BASE]: "",
  [APP_CONFIG_KEYS.SISTEMA_LOGO_URL]: "",
  [APP_CONFIG_KEYS.SISTEMA_COR_PRIMARIA]: "#8A05BE",
  [APP_CONFIG_KEYS.SISTEMA_COR_SECUNDARIA]: "#06b6d4",
  [APP_CONFIG_KEYS.SISTEMA_COR_ACCENT]: "#22c55e",
  [APP_CONFIG_KEYS.SISTEMA_TIMEZONE]: "America/Sao_Paulo",
  [APP_CONFIG_KEYS.SISTEMA_LOCALE]: "pt-BR",
  [APP_CONFIG_KEYS.SISTEMA_CURRENCY]: "BRL",
  [APP_CONFIG_KEYS.SISTEMA_MANUTENCAO]: false,
  [APP_CONFIG_KEYS.NEGOCIO_SCORE]: {
    formula: "weighted",
    pesos: { engajamento: 0.4, volume: 0.3, recencia: 0.3 },
    notas: "Ajuste pesos; consumo via useAppConfig().",
  },
  [APP_CONFIG_KEYS.NEGOCIO_ECONOMIA]: { moeda_padrao: "BRL", arredondamento: 2 },
  [APP_CONFIG_KEYS.NEGOCIO_LIMITES]: { max_clientes_por_gestor: 200, max_upload_mb: 10 },
  [APP_CONFIG_KEYS.NEGOCIO_REGRAS_NEGOCIO]: {
    taxa_gestao_pct: 10,
    taxa_emissao_pct: 5,
    desconto_fidelidade_pct: 15,
    validade_milhas_meses: 24,
    alerta_vencimento_dias: 30,
    alertar_cliente_milhas: true,
    kanban_colunas: ["Novo", "Em contato", "Reunião", "Proposta", "Cliente"],
    sla_resposta_leads_horas: 24,
  },
  [APP_CONFIG_KEYS.FINANCEIRO_CATEGORIAS]: {
    receita: ["assinatura_equipe", "assinatura_cliente", "agencia_viagens"],
    despesa: ["marketing", "ferramentas", "equipe", "infraestrutura"],
  },
  [APP_CONFIG_KEYS.FINANCEIRO_TAXAS]: { iva_padrao: 0, taxa_servico_pct: 0 },
  [APP_CONFIG_KEYS.FINANCEIRO_PAGAMENTOS]: {
    stripe_secret_key: "",
    stripe_webhook_secret: "",
    stripe_mode: "sandbox",
    moeda_padrao: "BRL",
    taxa_stripe_pct: 2.9,
    metodo_cobranca_padrao: "pix",
  },
  [APP_CONFIG_KEYS.VIAGENS_STATUS]: ["planejada", "em_andamento", "chegada_confirmada", "finalizada"],
  [APP_CONFIG_KEYS.VIAGENS_ALERTAS]: { pre_viagem_horas: 24, pos_viagem_horas: 48 },
  [APP_CONFIG_KEYS.NOTIFICACOES_TEMPLATES]: {
    boas_vindas: "Olá {{nome}}, bem-vindo ao {{app_nome}}.",
    lembrete_viagem: "A sua viagem para {{destino}} aproxima-se.",
  },
  [APP_CONFIG_KEYS.NOTIFICACOES_CANAIS]: {
    email_provider: "off",
    email_api_key: "",
    email_remetente: "",
    nome_remetente: "Gest Miles",
    notif_novo_lead: true,
    notif_assinatura_vencendo: true,
    notif_cliente_inativo: true,
    notif_relatorio_mensal: true,
    notif_erro_operacional: true,
    whatsapp_numero: "",
    whatsapp_mensagem_boas_vindas: "",
  },
  [APP_CONFIG_KEYS.INTEGRACOES_DETALHES]: {
    n8n_webhook_url: "",
    stripe_webhook_endpoint: "",
    ultimas_chamadas: [],
  },
};
